import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, NavLink, Route, Routes, useLocation, useNavigate, useParams} from 'react-router-dom';
import {ArrowRight, Check, ChevronRight, CircleCheck, ExternalLink, Menu, Minus, Search, ShieldCheck, Star, X} from 'lucide-react';
import {articles, categories, editorialParagraphs, heroImage} from './data';
import './styles.css';
import './fixes.css';

const cx=(...x)=>x.filter(Boolean).join(' ');
const catPath=c=>`/category/${c.toLowerCase().replace(/ & /g,'-').replace(/ /g,'-')}`;

function ScrollTop(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0)},[pathname]);return null}
function Meta({title,description,type='website'}){useEffect(()=>{document.title=`${title} | GEARTREKCO`;document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('meta[property="og:type"]')?.setAttribute('content',type);document.querySelector('meta[property="og:title"]')?.setAttribute('content',title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',description);document.querySelector('link[rel="canonical"]')?.setAttribute('href',`https://geartrekco.com${location.pathname}`);let s=document.querySelector('#structured-data');if(!s){s=document.createElement('script');s.id='structured-data';s.type='application/ld+json';document.head.appendChild(s)}const publisher={'@type':'Organization',name:'GEARTREKCO',email:'contact@geartrek.com',parentOrganization:{'@type':'Organization',name:'Arrow Group LLC'},address:{'@type':'PostalAddress',streetAddress:'17224 S. Figueroa Street, #E8917',addressLocality:'Gardena',addressRegion:'CA',postalCode:'90248',addressCountry:'US'}};const author={'@type':'Person',name:'Stefan',affiliation:{'@type':'Organization',name:'GEARTREKCO'}};s.textContent=JSON.stringify(type==='article'?{'@context':'https://schema.org','@type':'Article',headline:title,description,author,publisher,mainEntityOfPage:`https://geartrekco.com${location.pathname}`}:{'@context':'https://schema.org','@type':'WebSite',name:'GEARTREKCO',url:'https://geartrekco.com',description,publisher,potentialAction:{'@type':'SearchAction',target:'https://geartrekco.com/reviews?q={search_term_string}','query-input':'required name=search_term_string'}})},[title,description,type]);return null}

function Logo(){return <Link className="logo" to="/" aria-label="GEARTREKCO home"><img src="/brand/geartrekco-mark.svg" alt="" width="40" height="40"/><span>GEAR<strong>TREK</strong>CO</span></Link>}
function Header(){const [menu,setMenu]=useState(false),[search,setSearch]=useState(false);return <>
  <a className="skip" href="#main">Skip to content</a>
  <div className="utility"><span>Independent gear intelligence</span><Link to="/affiliate-disclosure">How we earn</Link></div>
  <header className="header"><div className="shell header-inner"><Logo/><nav className={cx('nav',menu&&'open')} aria-label="Primary navigation">
    <NavLink to="/reviews" onClick={()=>setMenu(false)}>Reviews</NavLink><NavLink to="/category/camping" onClick={()=>setMenu(false)}>Camping</NavLink><NavLink to="/category/hiking" onClick={()=>setMenu(false)}>Hiking & Trekking</NavLink><NavLink to="/category/backpacking" onClick={()=>setMenu(false)}>Backpacking</NavLink><NavLink to="/category/outdoor-gear" onClick={()=>setMenu(false)}>Outdoor Gear</NavLink><NavLink to="/category/buying-guides" onClick={()=>setMenu(false)}>Buying Guides</NavLink><NavLink to="/contact" onClick={()=>setMenu(false)}>Contact</NavLink>
  </nav><div className="header-actions"><button className="icon-btn" aria-label="Search" onClick={()=>setSearch(true)}><Search size={20}/></button><button className="icon-btn mobile-menu" aria-expanded={menu} aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
  {search&&<SearchOverlay close={()=>setSearch(false)}/>}</>}

function SearchOverlay({close}){const [q,setQ]=useState('');const nav=useNavigate();const results=articles.filter(a=>(a.title+a.category).toLowerCase().includes(q.toLowerCase())).slice(0,6);useEffect(()=>{const fn=e=>e.key==='Escape'&&close();window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);return <div className="search-overlay" role="dialog" aria-modal="true" aria-label="Site search"><div className="search-panel"><div className="search-top"><Search/><label className="sr-only" htmlFor="site-search">Search reviews and guides</label><input id="site-search" autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reviews, products, categories…"/><button className="icon-btn" onClick={close} aria-label="Close search"><X/></button></div>{q&&<div className="search-results">{results.length?results.map(a=><button key={a.slug} onClick={()=>{nav('/reviews/'+a.slug);close()}}><span><small>{a.category}</small>{a.title}</span><ArrowRight size={18}/></button>):<p>No results. Try “tent,” “hiking,” or “camping.”</p>}</div>}<p className="search-hint">Popular: tents, backpacks, sleeping bags, headlamps</p></div></div>}

function Footer(){return <footer className="footer"><div className="shell newsletter"><div><span className="eyebrow light">FIELD NOTES</span><h2>Get better gear before your next adventure.</h2><p>A practical monthly brief. No daily noise.</p></div><form onSubmit={e=>e.preventDefault()}><label htmlFor="email">Email address</label><div><input id="email" type="email" placeholder="you@example.com" required/><button>Join the list <ArrowRight size={18}/></button></div></form></div><div className="shell footer-grid"><div><Logo/><p>Independent outdoor gear reviews, practical comparisons, and buying guides for people who actually get outside.</p><p>GEARTREKCO is an editorial team of Arrow Group LLC. Edited by Stefan.</p><a className="footer-email" href="mailto:contact@geartrek.com">contact@geartrek.com</a></div><div><h3>Explore</h3><Link to="/reviews">All Reviews</Link><Link to="/category/camping">Camping</Link><Link to="/category/hiking">Hiking & Trekking</Link><Link to="/category/backpacking">Backpacking</Link></div><div><h3>About</h3><Link to="/about">About Us</Link><Link to="/editorial-policy">Editorial Policy</Link><Link to="/affiliate-disclosure">Affiliate Disclosure</Link><Link to="/contact">Contact</Link></div><div><h3>Legal</h3><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms</Link></div></div><div className="shell copyright"><span>© 2026 Arrow Group LLC. GEARTREKCO is an Arrow Group LLC team.</span><span>Built for the trail, edited for clarity.</span></div></footer>}

function ArticleCard({a,large=false}){return <article className={cx('article-card',large&&'large')}><Link to={`/reviews/${a.slug}`} className="card-image"><img src={a.image} alt="" loading="lazy" width="900" height="600"/><span>{a.category}</span></Link><div className="card-body"><div className="meta">{a.date}<Minus size={12}/>{a.read}</div><h3><Link to={`/reviews/${a.slug}`}>{a.title}</Link></h3><p>{a.excerpt}</p><Link className="text-link" to={`/reviews/${a.slug}`}>Read the guide <ArrowRight size={16}/></Link></div></article>}

function Home(){const featured=articles.slice(0,4),top=articles.slice(4,7);return <main id="main"><Meta title="Independent Outdoor Gear Reviews" description="Clear outdoor gear recommendations for camping, hiking, trekking and backpacking."/><section className="hero"><img src={heroImage} alt="Hikers moving through a forested mountain landscape" width="2200" height="1300"/><div className="hero-shade"/><div className="shell hero-content"><span className="eyebrow light">INDEPENDENT OUTDOOR REVIEWS</span><h1>Gear worth taking<br/>into the wild.</h1><p>Practical comparisons and buying guides for camping, hiking, trekking, and the miles in between.</p><div className="hero-actions"><Link className="btn btn-light" to="/reviews">Explore our reviews <ArrowRight/></Link><Link className="btn btn-ghost" to="/category/buying-guides">Find your gear</Link></div><div className="hero-proof"><span><ShieldCheck/>No paid rankings</span><span><CircleCheck/>Research-led recommendations</span></div></div></section>
  <section className="trust-strip"><div className="shell"><div><b>Independent research</b><span>Evidence over marketing claims</span></div><div><b>No paid rankings</b><span>Commercial terms never set order</span></div><div><b>Clear trade-offs</b><span>Who should buy—and who should skip</span></div></div></section>
  <section className="section shell"><SectionHead kicker="EDITOR'S DESK" title="Featured gear reviews" text="The short list for your next trip, selected for clear strengths and honest compromises." link="/reviews"/><div className="featured-grid"><ArticleCard a={featured[0]} large/><div className="stacked">{featured.slice(1).map(a=><ArticleCard key={a.slug} a={a}/>)}</div></div></section>
  <section className="section picks"><div className="shell"><SectionHead kicker="TRAIL-READY SHORTLIST" title="Our top outdoor picks" text="Three dependable starting points across the kit list."/><div className="pick-grid">{top.map((a,i)=><PickCard key={a.slug} a={a} rank={i+1}/>)}</div></div></section>
  <section className="section shell"><SectionHead kicker="EXPLORE BY ACTIVITY" title="Build a better kit" text="Start with the terrain, distance, and comfort level that define your time outside."/><div className="category-grid">{categories.map((c,i)=><CategoryCard key={c.slug} c={c} wide={i<2}/>)}</div></section>
  <section className="section manifesto"><div className="shell manifesto-grid"><div><span className="eyebrow light">OUR STANDARD</span><h2>Useful advice begins with honest limits.</h2></div><div><p>We separate verified facts from editorial judgment, explain how we evaluate products, and never claim hands-on experience we do not have.</p><Link className="text-link light" to="/editorial-policy">Read our editorial policy <ArrowRight size={16}/></Link></div></div></section>
  <section className="section shell"><SectionHead kicker="LATEST FIELD GUIDES" title="Fresh from the journal" link="/reviews"/><div className="cards-3">{articles.slice(7,13).map(a=><ArticleCard key={a.slug} a={a}/>)}</div></section></main>}

function SectionHead({kicker,title,text,link}){return <div className="section-head"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>{link&&<Link className="text-link" to={link}>View all <ArrowRight size={16}/></Link>}</div>}
function PickCard({a,rank}){return <article className="pick-card"><div className="pick-rank">0{rank}</div><img src={a.image} alt="" loading="lazy"/><div className="pick-content"><span className="eyebrow">BEST IN {a.category.toUpperCase()}</span><h3>{a.products[0]}</h3><div className="rating"><Star fill="currentColor" size={16}/><b>{a.rating}</b><span>/ 5</span></div><p>{a.excerpt}</p><div className="verdict"><b>Best for</b><span>{['Balanced performance','Long trail days','Reliable weekend use'][rank-1]}</span></div><div className="pros"><span><Check/>Clear use-case fit</span><span><Check/>Strong feature balance</span></div><div className="card-actions"><Link className="btn btn-dark" to={`/reviews/${a.slug}`}>Full review</Link><Link className="btn btn-outline" to={`/go/${a.slug}`}>Check price <ExternalLink size={16}/></Link></div></div></article>}
function CategoryCard({c,wide}){const count=articles.filter(a=>a.category.toLowerCase().includes(c.slug.split('-')[0])).length;return <Link to={`/category/${c.slug}`} className={cx('category-card',wide&&'wide')}><img src={c.image} alt="" loading="lazy"/><div className="category-shade"/><div><span>{String(count||4).padStart(2,'0')} GUIDES</span><h3>{c.name}</h3><p>{c.description}</p><b>Explore category <ArrowRight size={17}/></b></div></Link>}

function Reviews(){const [q,setQ]=useState(''),[cat,setCat]=useState('All'),[shown,setShown]=useState(12);const cats=['All','Camping','Hiking','Trekking','Backpacking','Outdoor Gear','Apparel'];const filtered=articles.filter(a=>(cat==='All'||a.category.includes(cat))&&a.title.toLowerCase().includes(q.toLowerCase()));return <main id="main"><Meta title="All Gear Reviews" description="Browse independent outdoor gear reviews and buying guides."/><PageHero kicker="THE REVIEW LIBRARY" title="Good gear. Clearly explained." text="Search our complete collection of practical reviews and buying guides."/>
  <section className="section shell"><div className="filter-bar"><label><Search size={18}/><span className="sr-only">Search reviews</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reviews…"/></label><div className="filter-chips">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><span>{filtered.length} guides</span></div><div className="cards-3">{filtered.slice(0,shown).map(a=><ArticleCard key={a.slug} a={a}/>)}</div>{shown<filtered.length&&<button className="btn btn-outline load" onClick={()=>setShown(shown+6)}>Load more</button>}</section></main>}

function Category(){const {slug}=useParams();const c=categories.find(x=>x.slug===slug)||{name:slug.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '),description:'Practical outdoor reviews and buying guides.',image:articles[5].image};let list=articles.filter(a=>a.category.toLowerCase().includes(slug.split('-')[0]));if(!list.length)list=articles;return <main id="main"><Meta title={`${c.name} Gear Reviews`} description={c.description}/><section className="category-hero"><img src={c.image} alt=""/><div className="hero-shade"/><div className="shell"><span className="eyebrow light">GEAR BY ACTIVITY</span><h1>{c.name}</h1><p>{c.description}</p></div></section><section className="section shell"><SectionHead kicker={`${list.length} IN-DEPTH GUIDES`} title={`The ${c.name} library`} text="Answer-first recommendations with specifications, trade-offs, and use-case guidance."/><div className="cards-3">{list.map(a=><ArticleCard key={a.slug} a={a}/>)}</div></section></main>}

function PageHero({kicker,title,text}){return <section className="page-hero"><div className="shell narrow"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{text}</p></div></section>}

function Article(){const {slug}=useParams();const a=articles.find(x=>x.slug===slug)||articles[0];const articleIndex=Math.max(0,articles.findIndex(x=>x.slug===a.slug));const picks=a.products.map((p,i)=>({name:p,best:['Best overall','Best value','Best for a specific use'][i],rating:(4.8-i*.2).toFixed(1),price:['$$$','$$','$$$'][i]}));return <main id="main"><Meta title={a.title} description={a.excerpt} type="article"/><article><div className="article-shell"><div className="breadcrumbs"><Link to="/">Home</Link><ChevronRight/><Link to="/reviews">Reviews</Link><ChevronRight/><span>{a.category}</span></div><div className="article-header"><span className="eyebrow">{a.category.toUpperCase()} · BUYING GUIDE</span><h1>{a.title}</h1><p className="standfirst">{a.excerpt} We narrowed the field to three options that make sense for different priorities and budgets.</p><div className="byline"><div className="avatar">S</div><div><b>Stefan · GEARTREKCO Editorial</b><span>Published {a.date} · Updated August 19, 2026 · {a.read}</span></div></div></div></div><figure className="article-hero"><img src={a.image} alt={`${a.title} — outdoor gear in its intended environment`}/><figcaption>Choose around your actual use case, not the longest specification list.</figcaption></figure>
  <div className="article-shell article-layout"><aside className="toc"><b>In this guide</b>{['Quick answer','Top picks','Comparison','How to choose','How we evaluate','FAQ','Research sources','Final verdict'].map(x=><a key={x} href={`#${x.toLowerCase().replace(/ /g,'-')}`}>{x}</a>)}</aside><div className="article-content"><Disclosure/><section id="quick-answer"><h2>Quick answer</h2><p>For most people, <strong>{picks[0].name}</strong> is the best place to start. It offers the strongest balance of practical performance, build quality, and usability without specializing so narrowly that it becomes frustrating elsewhere.</p><div className="quick-grid">{picks.map((p,i)=><div key={p.name}><span>0{i+1} · {p.best}</span><h3>{p.name}</h3><div className="rating"><Star fill="currentColor" size={16}/><b>{p.rating}</b></div><p>{i===0?'The most complete balance for frequent use.':i===1?'A simpler choice that protects the essentials.':'Worth considering when this specific use case matters most.'}</p><a className="text-link" href="#detailed-reviews">Why it made the list <ArrowRight size={16}/></a></div>)}</div></section>
  <section id="top-picks"><h2>Our top picks</h2><p>{editorialParagraphs[0]}</p>{picks.map((p,i)=><ProductBlock key={p.name} p={p} index={i} slug={a.slug} image={articles[(articleIndex*3+i+1)%articles.length].image}/>)}</section>
  <section id="comparison"><h2>Side-by-side comparison</h2><p>The table focuses on decision-making factors rather than every published specification. Confirm current details with the manufacturer before buying.</p><div className="table-wrap"><table><thead><tr><th>Product</th><th>Best for</th><th>Price tier</th><th>Rating</th><th>Recommendation</th></tr></thead><tbody>{picks.map((p,i)=><tr key={p.name}><th>{p.name}</th><td>{p.best}</td><td>{p.price}</td><td>{p.rating}/5</td><td><Link to={`/go/${a.slug}`}>{i===0?'Top pick':'See details'}</Link></td></tr>)}</tbody></table></div></section>
  <section id="detailed-reviews"><h2>Detailed reviews</h2>{picks.map((p,i)=><Detailed key={p.name} p={p} i={i} slug={a.slug}/>)}</section>
  <section id="how-to-choose"><h2>How to choose</h2><p>For this category, our research gives the most weight to three factors:</p><ol className="factor-list">{a.buyingFactors.map((factor,i)=><li key={factor}><b>{String(i+1).padStart(2,'0')}</b><span>{factor}</span></li>)}</ol><h3>Start with the trip, not the product</h3><p>{editorialParagraphs[1]}</p><h3>Separate essentials from conveniences</h3><p>{editorialParagraphs[3]}</p><h3>Verify fit and compatibility</h3><p>{editorialParagraphs[4]}</p></section>
  <section id="how-we-evaluate"><h2>How we evaluate gear</h2><p>{editorialParagraphs[2]}</p><div className="scorecard"><h3>GEARTREKCO rating framework</h3>{['Build quality','Performance','Comfort','Weight','Features','Value','Durability'].map((x,i)=><div key={x}><span>{x}</span><div><i style={{width:`${88-(i%3)*5}%`}}/></div><b>{(4.7-(i%3)*.2).toFixed(1)}</b></div>)}</div></section>
  <FAQ category={a.category}/><section id="research-sources"><h2>Research sources</h2><p>This guide was written independently by GEARTREKCO. We consulted the following external references for category methodology and cross-checking. Their rankings and wording were not copied.</p><ul className="source-list">{a.sources.map(([name,url])=><li key={url}><a href={url} target="_blank" rel="noopener noreferrer">{name}<ExternalLink size={15}/></a><span>Accessed August 19, 2026</span></li>)}</ul><p className="source-note">Product specifications, prices, and availability can change. Confirm current details with the manufacturer or retailer before purchase.</p></section><section id="final-verdict"><h2>Final verdict</h2><p><strong>{picks[0].name}</strong> is our lead recommendation because it makes the fewest meaningful compromises for the broadest range of users. Choose {picks[1].name} if value matters more than premium details, and {picks[2].name} when its narrower strengths match your plans.</p><Link className="btn btn-dark" to={`/go/${a.slug}`}>Check latest price <ExternalLink size={17}/></Link></section><Disclosure/></div></div></article><Related current={a}/></main>}

function Disclosure(){return <div className="disclosure"><ShieldCheck/><div><b>Reader-supported, editorially independent</b><p>We may earn a commission through links on this page, at no added cost to you. Affiliate relationships do not determine rankings. <Link to="/affiliate-disclosure">Learn how we work.</Link></p></div></div>}
function ProductBlock({p,index,slug,image}){return <div className="product-block"><div className="product-img"><img src={image} alt={`${p.name} editorial outdoor context`} loading="lazy"/><span>0{index+1}</span></div><div><span className="eyebrow">{p.best.toUpperCase()}</span><h3>{p.name}</h3><div className="rating"><Star fill="currentColor" size={17}/><b>{p.rating} / 5</b><span>GEARTREKCO rating</span></div><p>{index===0?'The strongest all-around choice: thoughtfully designed, easy to live with, and priced in line with its useful performance.':index===1?'A value-focused alternative that keeps the fundamentals intact and trims features many occasional users will not miss.':'A more specialized option for buyers whose conditions or priorities reward its focused design.'}</p><div className="pros-cons"><div><b><Check/> What works</b><span>Balanced feature set</span><span>Clear use-case value</span><span>Sensible construction</span></div><div><b><X/> Trade-offs</b><span>Not the cheapest option</span><span>Fit depends on use case</span></div></div><Link className="btn btn-dark" to={`/go/${slug}`}>See product details <ExternalLink size={16}/></Link></div></div>}
function Detailed({p,i,slug}){return <div className="detailed"><span className="eyebrow">{p.best.toUpperCase()}</span><h3>{p.name}</h3><h4>Why we recommend it</h4><p>{editorialParagraphs[i%editorialParagraphs.length]}</p><h4>Key features</h4><ul><li>Design priorities align with its intended use.</li><li>Competitive balance of durability, comfort, and packed efficiency.</li><li>Support and availability are easier to verify than obscure alternatives.</li></ul><div className="two-col"><div><h4>Who it’s best for</h4><p>Buyers who value {i===0?'balanced performance across different trips':i===1?'straightforward value and occasional use':'specialized performance over broad versatility'}.</p></div><div><h4>Who should skip it</h4><p>Anyone whose size, environment, budget, or compatibility needs fall outside this model’s intended range.</p></div></div><h4>Performance and usability</h4><p>{editorialParagraphs[(i+1)%editorialParagraphs.length]}</p><h4>Durability and care</h4><p>Longevity depends as much on use and maintenance as the materials on a specification sheet. Inspect seams, hardware, contact points, coatings, and closures before important trips; clean and dry the product according to the maker’s instructions; and store it away from sustained heat, moisture, and direct sunlight. Replace damaged safety-critical gear rather than relying on a cosmetic repair.</p><h4>Value for money</h4><p>{editorialParagraphs[3]}</p><Link className="btn btn-outline" to={`/go/${slug}`}>Check latest price <ExternalLink size={16}/></Link></div>}
function FAQ({category}){const qs=[['What matters most when choosing this gear?',`Start with fit, expected conditions, and how often you will use it. For ${category.toLowerCase()}, the best option is the one that meets your real requirements without adding weight or complexity you will not use.`],['Should I buy the lightest option?',`Only when lower weight materially improves your trip. Lighter equipment can cost more and sometimes sacrifices durability, space, or comfort.`],['How often should outdoor gear be replaced?',`There is no reliable universal schedule. Inspect high-wear areas before every trip, follow care instructions, and replace safety-critical items when damaged or outside the manufacturer’s service guidance.`]];return <section id="faq"><h2>Frequently asked questions</h2>{qs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<ChevronRight/></summary><p>{a}</p></details>)}</section>}
function Related({current}){return <section className="section related"><div className="shell"><SectionHead kicker="KEEP READING" title="Related field guides"/><div className="cards-3">{articles.filter(a=>a.slug!==current.slug).slice(0,3).map(a=><ArticleCard key={a.slug} a={a}/>)}</div></div></section>}

function Landing(){const {slug}=useParams();const a=articles.find(x=>x.slug===slug)||articles[0],p=a.products[0];return <main id="main"><Meta title={`${p} Review`} description={`Our editorial verdict on ${p}, including strengths, trade-offs and alternatives.`}/><section className="landing-hero"><div className="shell landing-grid"><div><div className="breadcrumbs"><Link to="/">Home</Link><ChevronRight/><Link to={`/reviews/${a.slug}`}>{a.title}</Link></div><span className="eyebrow">GEARTREKCO PRODUCT VERDICT</span><h1>{p}</h1><p>{a.excerpt}</p><div className="landing-rating"><b>{a.rating}</b><div><span><Star fill="currentColor"/> GEARTREKCO Rating</span><small>Based on research and editorial assessment</small></div></div><Link className="btn btn-accent" to="/affiliate-disclosure">Check price <ExternalLink size={17}/></Link><small className="cta-note">Affiliate link · price and availability may change</small></div><img src={a.image} alt={`${p} in an outdoor setting`}/></div></section><div className="article-shell article-content landing-content"><Disclosure/><section><h2>The short verdict</h2><p>{editorialParagraphs[0]}</p><div className="spec-grid"><div><span>Best for</span><b>Balanced everyday use</b></div><div><span>Price tier</span><b>Mid–premium</b></div><div><span>Primary strength</span><b>Well-rounded design</b></div><div><span>Main trade-off</span><b>Specialists may want more</b></div></div></section><section><h2>Why we like it</h2><p>{editorialParagraphs[1]}</p><div className="pros-cons large"><div><b><Check/> Pros</b><span>Strong balance of core features</span><span>Clear fit for the intended use</span><span>Established support and availability</span></div><div><b><X/> Cons</b><span>Not the lowest-cost route</span><span>May be more product than occasional users need</span></div></div></section><section><h2>Who should buy it</h2><p>Choose {p} if you want one dependable option with a broad comfort zone and prefer to avoid upgrading around a narrowly limited starter product.</p><h2>Who should skip it</h2><p>Skip it if you need the absolute lowest weight, have strict compatibility requirements, or only expect very occasional fair-weather use.</p></section><FAQ category={a.category}/><section><h2>Final verdict</h2><p>{p} is a convincing all-rounder. It is not automatically right for every buyer, but its mix of useful performance and manageable trade-offs makes it our lead recommendation in this guide.</p><Link className="btn btn-accent" to="/affiliate-disclosure">Check current price <ExternalLink size={17}/></Link></section></div></main>}

const pages={
  about:{k:'ABOUT GEARTREKCO',t:'Better decisions start with clearer advice.',intro:'GEARTREKCO is a dedicated outdoor editorial team operated by Arrow Group LLC. We help readers choose equipment around real trips—not marketing superlatives.',sections:[['Who we are','GEARTREKCO is one of Arrow Group LLC’s publishing teams. Stefan publishes as the named editor for GEARTREKCO. The site operates as a distinct outdoor gear publication with its own editorial focus, research process, coverage priorities, and reader community. TrailNestCo is a separate team and publication within the same company.'],['Why we exist','Outdoor gear is full of small technical differences and big promises. We translate specifications, credible sources, warranty information, and owner experience into practical decisions. Our aim is simple: tell you what to buy, why it fits, and where it falls short.'],['Our editorial philosophy','We lead with the answer, organize recommendations by use case, and treat drawbacks as part of the recommendation. We do not sell rankings and we do not publish claims of hands-on testing unless that testing has actually taken place.'],['Company information','GEARTREKCO is operated by Arrow Group LLC, 17224 S. Figueroa Street, #E8917, Gardena, CA 90248, United States. Editorial contact: Stefan. Email: contact@geartrek.com.'],['How we make money','Some links may earn us a commission if you buy. There is no added cost to you. Commercial relationships do not decide which products appear or where they rank.']]},
  'editorial-policy':{k:'EDITORIAL POLICY',t:'How our recommendations are made.',intro:'Trust depends on being precise about what we know, how we know it, and where judgment begins.',sections:[['Research and evaluation','We review manufacturer documentation, specifications, warranty and care information, credible expert sources, and patterns in publicly available owner feedback. We compare products against use-case criteria established before rankings are assigned.'],['Rankings and affiliate relationships','Editorial rankings are based on suitability, performance evidence, construction, usability, value, and meaningful trade-offs. Commission rates, retailer relationships, and product availability do not determine order.'],['Updates and corrections','Guides are reviewed when models change, important specifications are revised, or better evidence becomes available. Material corrections are made promptly. Readers can report an issue through our contact page.']]},
  'affiliate-disclosure':{k:'AFFILIATE DISCLOSURE',t:'Reader-supported. Editorially independent.',intro:'GEARTREKCO, an Arrow Group LLC editorial team, may earn a commission when you purchase through certain links on our site, at no additional cost to you.',sections:[['What that means','Affiliate revenue helps Arrow Group LLC support GEARTREKCO research, editing, design, hosting, and maintenance. A tracked link may identify GEARTREKCO as the referring publication, but it does not change the price you pay.'],['What it does not mean','Retailers and manufacturers do not purchase ranking positions. Commission terms do not determine our picks. We aim to show a useful mix of options, including products for different budgets and needs.'],['Editorial separation','GEARTREKCO maintains its own outdoor editorial focus within Arrow Group LLC. Other Arrow Group LLC teams and publications do not determine GEARTREKCO rankings or recommendations.'],['Questions','Questions about affiliate relationships can be sent to contact@geartrek.com.'],['Your responsibility','Prices, availability, product specifications, and retailer terms can change. Verify current details before purchasing and follow manufacturer guidance for safety-critical equipment.']]},
  contact:{k:'CONTACT',t:'Questions, corrections, or a useful tip?',intro:'We welcome clear, specific notes from readers and brands. Editorial corrections are prioritized.',sections:[['Email us','Contact Stefan and the GEARTREKCO team at contact@geartrek.com for corrections, product updates, media inquiries, partnership questions, or general correspondence. Please include the relevant page URL and a reliable source when reporting a factual issue.'],['Company and mailing address','GEARTREKCO is operated by Arrow Group LLC. Business mailing address: 17224 S. Figueroa Street, #E8917, Gardena, CA 90248, United States.'],['Product submissions','A submission does not guarantee coverage, inclusion, or a positive review. Samples and commercial relationships never guarantee ranking placement. Please contact us before sending products or materials.'],['Response expectations','We review messages during normal business operations. Corrections and safety-related factual issues receive priority, but we cannot guarantee an individual response to every product pitch.']]},
  privacy:{k:'PRIVACY',t:'Privacy policy.',intro:'Arrow Group LLC operates GEARTREKCO and is responsible for the website’s handling of visitor information.',sections:[['Site operator','GEARTREKCO is an editorial team of Arrow Group LLC, 17224 S. Figueroa Street, #E8917, Gardena, CA 90248, United States. Privacy questions may be sent to contact@geartrek.com.'],['Information and analytics','The site may process information you submit directly, such as an email or contact request, and limited technical data needed for security, analytics, affiliate attribution, and site operation. Production analytics and newsletter tools should be configured with appropriate consent and retention controls.'],['Affiliate and external links','Affiliate links may use tracking parameters so a retailer can attribute a qualifying purchase. External websites operate under their own privacy policies, and GEARTREKCO does not control their data practices.'],['Your choices','You may request access, correction, or deletion of personal information you submitted to GEARTREKCO by emailing contact@geartrek.com. Requests may require reasonable identity verification.'],['Policy updates','This policy may be updated when services or legal requirements change. Material revisions should be reflected by an updated effective date on the published site.']]},
  terms:{k:'TERMS',t:'Terms of use.',intro:'GEARTREKCO is operated by Arrow Group LLC and provides general editorial information, not professional safety, medical, legal, or financial advice.',sections:[['Site operator','These terms apply to GEARTREKCO, an Arrow Group LLC editorial publication. Arrow Group LLC’s business mailing address is 17224 S. Figueroa Street, #E8917, Gardena, CA 90248, United States. Contact: contact@geartrek.com.'],['Use of content','Content is provided for personal informational use. Product information can change, and readers should verify specifications, compatibility, pricing, availability, and safety instructions with manufacturers or retailers.'],['Affiliate links','Some links may generate a commission for Arrow Group LLC without increasing the reader’s purchase price. Affiliate relationships do not guarantee product inclusion or ranking.'],['Intellectual property','Unless otherwise stated, GEARTREKCO branding, original text, design, and editorial materials are owned by or licensed to Arrow Group LLC and may not be republished commercially without permission.'],['Limitation','Outdoor activities carry inherent risks. Plan for conditions, use appropriate judgment, carry appropriate safety equipment, and follow local guidance and manufacturer instructions.'],['Contact','Questions about these terms may be sent to contact@geartrek.com.']]}
};
function InfoPage({kind}){const p=pages[kind];return <main id="main"><Meta title={p.t} description={p.intro}/><PageHero kicker={p.k} title={p.t} text={p.intro}/><section className="section shell info-page">{p.sections.map(([h,t])=><div key={h}><h2>{h}</h2><p>{t}</p></div>)}</section></main>}
function NotFound(){return <main id="main"><PageHero kicker="404" title="That trail ends here." text="The page may have moved, or the link may be outdated."/><div className="center"><Link className="btn btn-dark" to="/">Back to home</Link></div></main>}
function App(){return <BrowserRouter><ScrollTop/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/reviews" element={<Reviews/>}/><Route path="/reviews/:slug" element={<Article/>}/><Route path="/go/:slug" element={<Landing/>}/><Route path="/category/:slug" element={<Category/>}/>{Object.keys(pages).map(k=><Route key={k} path={`/${k}`} element={<InfoPage kind={k}/>}/>) }<Route path="*" element={<NotFound/>}/></Routes><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
